<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL1Rd4UJ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL1Rd4UJ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerL1Rd4UJ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerL1Rd4UJ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerL1Rd4UJ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'L1Rd4UJ',
    'container.build_id' => 'ea9a38da',
    'container.build_time' => 1527755912,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerL1Rd4UJ');
